#!/bin/bash
# ============================================
# macOS Dev Environment Setup Script
# Usage:
#   ./setup-mac-dev.sh terminal    - Fish + Starship + Ghostty
#   ./setup-mac-dev.sh vscode      - VS Code settings + extensions
#   ./setup-mac-dev.sh all         - Everything (default)
# ============================================

set -e

MODE="${1:-all}"
TERMINAL_SUMMARY=()

add_terminal_summary() {
    local item="$1"
    TERMINAL_SUMMARY+=("$item")
}

print_terminal_summary() {
    local i=1
    local item
    if [[ "${#TERMINAL_SUMMARY[@]}" -eq 0 ]]; then
        return
    fi

    echo ""
    echo "📋 Terminal changes summary:"
    for item in "${TERMINAL_SUMMARY[@]}"; do
        echo "  $i. $item"
        i=$((i + 1))
    done
}

print_terminal_next_steps() {
    echo ""
    echo "🧭 Next steps:"
    echo "  1. Quit and reopen Ghostty to apply glass blur and theme updates."
    echo "  2. Open a new terminal tab and verify Starship powerline symbols render correctly."
    echo "  3. If the default shell is still not fish, run: chsh -s \"$(resolve_bin fish)\""
    echo "  4. If prompt looks wrong, run: exec fish"
}

ensure_formula_installed() {
    local formula="$1"
    if brew list --formula "$formula" &> /dev/null; then
        echo "✅ $formula already installed (skip)"
        add_terminal_summary "brew formula already present: $formula (idempotent skip)"
        return
    fi

    echo "📦 Installing $formula..."
    brew install "$formula"
    add_terminal_summary "installed brew formula: $formula"
}

ensure_cask_installed() {
    local cask="$1"
    if brew list --cask "$cask" &> /dev/null; then
        echo "✅ $cask already installed (skip)"
        add_terminal_summary "brew cask already present: $cask (idempotent skip)"
        return
    fi

    echo "📦 Installing $cask..."
    brew install --cask "$cask"
    add_terminal_summary "installed brew cask: $cask"
}

backup_file() {
    local target="$1"
    if [[ -f "$target" ]]; then
        local backup="${target}.bak.$(date +%Y%m%d%H%M%S)"
        cp "$target" "$backup"
        echo "🗂️  Backed up $target -> $backup"
        add_terminal_summary "backup created: $target -> $backup"
    fi
}

init_brew_shellenv() {
    local brew_bin=""
    if [[ -x /opt/homebrew/bin/brew ]]; then
        brew_bin="/opt/homebrew/bin/brew"
    elif [[ -x /usr/local/bin/brew ]]; then
        brew_bin="/usr/local/bin/brew"
    elif command -v brew &> /dev/null; then
        brew_bin="$(command -v brew)"
    fi

    if [[ -n "$brew_bin" ]]; then
        eval "$("$brew_bin" shellenv)"
        return 0
    fi

    return 1
}

resolve_bin() {
    local bin_name="$1"

    if command -v "$bin_name" &> /dev/null; then
        command -v "$bin_name"
        return 0
    fi

    if [[ -x "/opt/homebrew/bin/$bin_name" ]]; then
        echo "/opt/homebrew/bin/$bin_name"
        return 0
    fi

    if [[ -x "/usr/local/bin/$bin_name" ]]; then
        echo "/usr/local/bin/$bin_name"
        return 0
    fi

    return 1
}

current_login_shell() {
    dscacheutil -q user -a name "$USER" 2>/dev/null | awk '/^shell:/ {print $2; exit}'
}

strip_outer_quotes() {
    local s="$1"
    local len=${#s}
    local first_char last_char

    if [[ "$len" -lt 2 ]]; then
        printf '%s' "$s"
        return
    fi

    first_char="${s:0:1}"
    last_char="${s:$((len - 1)):1}"
    if [[ "$first_char" == "$last_char" ]] && [[ "$first_char" == "\"" || "$first_char" == "'" ]]; then
        printf '%s' "${s:1:$((len - 2))}"
        return
    fi

    printf '%s' "$s"
}

escape_for_double_quotes() {
    local s="$1"
    s="${s//\\/\\\\}"
    s="${s//\"/\\\"}"
    printf '%s' "$s"
}

migrate_zsh_to_fish() {
    local zsh_files out_file alias_tmp_file
    local file line trimmed entry key val raw
    local found_zsh_file=0
    local migrated_exports=0
    local migrated_paths=0
    local migrated_aliases=0
    local skipped_items=0

    zsh_files=("$HOME/.zshenv" "$HOME/.zprofile" "$HOME/.zshrc")
    out_file="$HOME/.config/fish/conf.d/90-zsh-migration.fish"

    for file in "${zsh_files[@]}"; do
        if [[ -f "$file" ]]; then
            found_zsh_file=1
            break
        fi
    done

    if [[ "$found_zsh_file" -eq 0 ]]; then
        echo "ℹ️  No zsh config files found, skipping zsh -> fish migration."
        return
    fi

    echo "🔄 Migrating zsh config to fish (best effort)..."
    mkdir -p "$HOME/.config/fish/conf.d"
    backup_file "$out_file"

    alias_tmp_file="$(mktemp)"
    {
        echo "# Auto-generated by setup-mac-dev.sh on $(date '+%Y-%m-%d %H:%M:%S')"
        echo "# Source: ~/.zshenv ~/.zprofile ~/.zshrc"
        echo "# This file migrates common exports / PATH / aliases from zsh to fish."
        echo "# Manual review recommended for plugin/framework-specific config."
    } > "$out_file"

    for file in "${zsh_files[@]}"; do
        [[ -f "$file" ]] || continue

        echo "" >> "$out_file"
        echo "# ---- from $file ----" >> "$out_file"

        while IFS= read -r line || [[ -n "$line" ]]; do
            trimmed="$(printf '%s\n' "$line" | sed -E 's/^[[:space:]]+//; s/[[:space:]]+$//')"
            [[ -z "$trimmed" || "$trimmed" == \#* ]] && continue

            if [[ "$trimmed" =~ ^export[[:space:]]+([A-Za-z_][A-Za-z0-9_]*)=(.*)$ ]]; then
                key="${BASH_REMATCH[1]}"
                val="${BASH_REMATCH[2]}"
                raw="$(strip_outer_quotes "$val")"

                if [[ "$key" == "PATH" ]]; then
                    local tokens token
                    IFS=':' read -r -a tokens <<< "$raw"
                    for token in "${tokens[@]}"; do
                        token="$(printf '%s\n' "$token" | sed -E 's/^[[:space:]]+//; s/[[:space:]]+$//')"
                        token="$(strip_outer_quotes "$token")"
                        if [[ -z "$token" || "$token" == *'$PATH'* || "$token" == *'${PATH}'* ]]; then
                            continue
                        fi
                        token="$(escape_for_double_quotes "$token")"
                        echo "fish_add_path -m \"$token\"" >> "$out_file"
                        migrated_paths=$((migrated_paths + 1))
                    done
                    continue
                fi

                if [[ "$raw" == *'$('* || "$raw" == *'`'* ]]; then
                    skipped_items=$((skipped_items + 1))
                    continue
                fi

                raw="$(escape_for_double_quotes "$raw")"
                echo "set -gx $key \"$raw\"" >> "$out_file"
                migrated_exports=$((migrated_exports + 1))
                continue
            fi

            if [[ "$trimmed" =~ ^alias[[:space:]]+([A-Za-z_][A-Za-z0-9_]*)=(.*)$ ]]; then
                key="${BASH_REMATCH[1]}"
                val="${BASH_REMATCH[2]}"
                raw="$(strip_outer_quotes "$val")"
                if [[ "$raw" == *'$('* || "$raw" == *'`'* ]]; then
                    skipped_items=$((skipped_items + 1))
                    continue
                fi
                raw="$(escape_for_double_quotes "$raw")"
                echo "    alias $key \"$raw\"" >> "$alias_tmp_file"
                migrated_aliases=$((migrated_aliases + 1))
            fi
        done < "$file"
    done

    if [[ "$migrated_aliases" -gt 0 ]]; then
        {
            echo ""
            echo "if status is-interactive"
            cat "$alias_tmp_file"
            echo "end"
        } >> "$out_file"
    fi

    rm -f "$alias_tmp_file"

    if [[ "$migrated_exports" -eq 0 && "$migrated_paths" -eq 0 && "$migrated_aliases" -eq 0 ]]; then
        echo "" >> "$out_file"
        echo "# No simple export/PATH/alias items were migrated from zsh files." >> "$out_file"
    fi

    echo "✅ zsh migration file written: $out_file"
    echo "   exports: $migrated_exports, paths: $migrated_paths, aliases: $migrated_aliases, skipped: $skipped_items"
    add_terminal_summary "migrated zsh -> fish to $out_file (exports=$migrated_exports, paths=$migrated_paths, aliases=$migrated_aliases, skipped=$skipped_items)"
}

print_terminal_status() {
    local login_shell fish_path starship_path ghostty_theme
    local has_catppuccin_powerline="no"

    login_shell="$(current_login_shell)"
    fish_path="$(resolve_bin fish || true)"
    starship_path="$(resolve_bin starship || true)"
    ghostty_theme="$(sed -n 's/^theme[[:space:]]*=[[:space:]]*//p' "$HOME/.config/ghostty/config" 2>/dev/null | head -n1)"

    if [[ -n "$starship_path" ]] && "$starship_path" preset --list 2>/dev/null | grep -qx 'catppuccin-powerline'; then
        has_catppuccin_powerline="yes"
    fi

    echo ""
    echo "🔎 Terminal status:"
    echo "   Login shell: ${login_shell:-unknown}"
    echo "   Fish binary: ${fish_path:-not found}"
    echo "   Starship binary: ${starship_path:-not found}"
    echo "   Starship preset catppuccin-powerline: $has_catppuccin_powerline"
    echo "   Ghostty theme: ${ghostty_theme:-not set}"
}

usage() {
    echo "Usage: $0 [terminal|vscode|all]"
    echo ""
    echo "  terminal  - Install & configure Fish, Starship, Ghostty"
    echo "  vscode    - Configure VS Code settings & install extensions"
    echo "  all       - Run both (default)"
    exit 1
}

if [[ "$MODE" != "terminal" && "$MODE" != "vscode" && "$MODE" != "all" ]]; then
    usage
fi

# ============================================
# Shared: Homebrew & Font
# ============================================
setup_shared() {
    # Homebrew
    if ! command -v brew &> /dev/null; then
        echo "📦 Installing Homebrew..."
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        if ! init_brew_shellenv; then
            echo "❌ Homebrew installed but brew command not found in expected paths."
            exit 1
        fi
    else
        echo "✅ Homebrew already installed"
        init_brew_shellenv || true
    fi

    # Font
    echo "🔤 Installing JetBrainsMono Nerd Font..."
    if brew list --cask font-jetbrains-mono-nerd-font &> /dev/null; then
        echo "✅ Font already installed"
    else
        brew install --cask font-jetbrains-mono-nerd-font
    fi
}

# ============================================
# Terminal: Fish + Starship + Ghostty
# ============================================
setup_terminal() {
    echo ""
    echo "🖥️  Setting up terminal environment..."
    TERMINAL_SUMMARY=()

    # Install packages
    echo "📦 Checking Fish, Starship, Ghostty..."
    ensure_formula_installed fish
    ensure_formula_installed starship
    ensure_cask_installed ghostty
    init_brew_shellenv || true

    # Set Fish as default shell
    FISH_PATH="$(resolve_bin fish || true)"
    LOGIN_SHELL="$(current_login_shell)"
    if [[ -z "$FISH_PATH" ]]; then
        echo "❌ Fish binary not found after install."
        exit 1
    fi

    if [[ "$LOGIN_SHELL" != "$FISH_PATH" ]]; then
        echo "🐟 Setting Fish as default shell..."
        if grep -qx "$FISH_PATH" /etc/shells; then
            if chsh -s "$FISH_PATH"; then
                echo "✅ Fish set as default shell"
                add_terminal_summary "set login shell to fish: $FISH_PATH"
            else
                echo "⚠️  Failed to set Fish as default shell. Run manually: chsh -s \"$FISH_PATH\""
                add_terminal_summary "could not set login shell automatically; manual action needed: chsh -s \"$FISH_PATH\""
            fi
        else
            echo "⚠️  Fish path not in /etc/shells: $FISH_PATH"
            echo "   Run manually:"
            echo "   sudo sh -c 'printf \"%s\\n\" \"$FISH_PATH\" >> /etc/shells' && chsh -s \"$FISH_PATH\""
            add_terminal_summary "fish path missing in /etc/shells; manual action needed to switch shell"
        fi
    else
        echo "✅ Fish is already default shell"
        add_terminal_summary "login shell already fish (idempotent skip)"
    fi

    # Configure Fish
    echo "🐟 Configuring Fish..."
    mkdir -p ~/.config/fish
    backup_file ~/.config/fish/config.fish
    cat > ~/.config/fish/config.fish << 'FISH_EOF'
fish_add_path -m $HOME/.local/bin /opt/homebrew/bin /usr/local/bin

if status is-interactive
    if test -x /opt/homebrew/bin/brew
        eval (/opt/homebrew/bin/brew shellenv | string collect)
    else if test -x /usr/local/bin/brew
        eval (/usr/local/bin/brew shellenv | string collect)
    end

    if type -q starship
        starship init fish | source
    end
end
FISH_EOF
    echo "✅ Fish configured"
    add_terminal_summary "wrote fish config: ~/.config/fish/config.fish (starship init + PATH)"
    migrate_zsh_to_fish

    # Configure Starship
    echo "⭐ Configuring Starship..."
    mkdir -p ~/.config
    backup_file ~/.config/starship.toml
    cat > ~/.config/starship.toml << 'STARSHIP_EOF'
"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](red)\
$os\
$username\
[](bg:peach fg:red)\
$directory\
[](bg:yellow fg:peach)\
$git_branch\
$git_status\
[](fg:yellow bg:green)\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[](fg:green bg:sapphire)\
$conda\
[](fg:sapphire bg:lavender)\
$time\
[ ](fg:lavender)\
$cmd_duration\
$line_break\
$character"""

palette = 'catppuccin_mocha'

[os]
disabled = false
style = "bg:red fg:crust"

[os.symbols]
Windows = ""
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "👨‍🚀"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
AOSC = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[username]
show_always = true
style_user = "bg:red fg:crust"
style_root = "bg:red fg:crust"
format = '[ $user]($style)'

[directory]
style = "bg:peach fg:crust"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:yellow"
format = '[[ $symbol $branch ](fg:crust bg:yellow)]($style)'

[git_status]
style = "bg:yellow"
format = '[[($all_status$ahead_behind )](fg:crust bg:yellow)]($style)'

[nodejs]
symbol = ""
style = "bg:green"
format = '[[ $symbol( $version) ](fg:crust bg:green)]($style)'

[c]
symbol = " "
style = "bg:green"
format = '[[ $symbol( $version) ](fg:crust bg:green)]($style)'

[rust]
symbol = ""
style = "bg:green"
format = '[[ $symbol( $version) ](fg:crust bg:green)]($style)'

[golang]
symbol = ""
style = "bg:green"
format = '[[ $symbol( $version) ](fg:crust bg:green)]($style)'

[php]
symbol = ""
style = "bg:green"
format = '[[ $symbol( $version) ](fg:crust bg:green)]($style)'

[java]
symbol = " "
style = "bg:green"
format = '[[ $symbol( $version) ](fg:crust bg:green)]($style)'

[kotlin]
symbol = ""
style = "bg:green"
format = '[[ $symbol( $version) ](fg:crust bg:green)]($style)'

[haskell]
symbol = ""
style = "bg:green"
format = '[[ $symbol( $version) ](fg:crust bg:green)]($style)'

[python]
symbol = ""
style = "bg:green"
format = '[[ $symbol( $version)(\\(#$virtualenv\\)) ](fg:crust bg:green)]($style)'

[docker_context]
symbol = ""
style = "bg:sapphire"
format = '[[ $symbol( $context) ](fg:crust bg:sapphire)]($style)'

[conda]
symbol = "  "
style = "fg:crust bg:sapphire"
format = '[$symbol$environment ]($style)'
ignore_base = false

[time]
disabled = false
time_format = "%R"
style = "bg:lavender"
format = '[[  $time ](fg:crust bg:lavender)]($style)'

[line_break]
disabled = true

[character]
disabled = false
success_symbol = '[❯](bold fg:green)'
error_symbol = '[❯](bold fg:red)'
vimcmd_symbol = '[❮](bold fg:green)'
vimcmd_replace_one_symbol = '[❮](bold fg:lavender)'
vimcmd_replace_symbol = '[❮](bold fg:lavender)'
vimcmd_visual_symbol = '[❮](bold fg:yellow)'

[cmd_duration]
show_milliseconds = true
format = " in $duration "
style = "bg:lavender"
disabled = false
show_notifications = true
min_time_to_notify = 45000

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
STARSHIP_EOF
    echo "✅ Starship configured"
    add_terminal_summary "wrote starship config: ~/.config/starship.toml (catppuccin mocha palette)"
    STARSHIP_PATH="$(resolve_bin starship || true)"
    if [[ -n "$STARSHIP_PATH" ]] && "$STARSHIP_PATH" preset --list 2>/dev/null | grep -qx 'catppuccin-powerline'; then
        echo "✅ Starship preset available: catppuccin-powerline"
        add_terminal_summary "verified starship preset: catppuccin-powerline"
    else
        echo "⚠️  Starship preset not found: catppuccin-powerline"
        add_terminal_summary "starship preset missing: catppuccin-powerline"
    fi

    # Configure Ghostty
    echo "👻 Configuring Ghostty..."
    mkdir -p ~/.config/ghostty
    backup_file ~/.config/ghostty/config
    cat > ~/.config/ghostty/config << 'GHOSTTY_EOF'
# Ghostty Configuration
# Reference: https://ghostty.org/docs/config/reference

# ============================================
# Font Settings
# ============================================
font-family = "JetBrainsMono Nerd Font"
font-size = 14

# ============================================
# Theme
# ============================================
theme = "Catppuccin Mocha"

# ============================================
# Cursor Settings
# ============================================
cursor-style = block
cursor-invert-fg-bg = true
cursor-opacity = 0.8

# ============================================
# Window Settings
# ============================================
window-vsync = true
background-opacity = 0.86
background-blur = macos-glass-regular
macos-titlebar-style = transparent
window-theme = auto
macos-window-shadow = true
window-save-state = always

# ============================================
# Behavior
# ============================================
copy-on-select = clipboard
link-url = true
mouse-hide-while-typing = true

# ============================================
# Appearance
# ============================================
adjust-cursor-thickness = 2
bold-is-bright = true

# ============================================
# Quick Terminal
# ============================================
keybind = global:ctrl+cmd+space=toggle_quick_terminal
quick-terminal-position = top
quick-terminal-size = 40%
quick-terminal-autohide = true
quick-terminal-screen = main
quick-terminal-space-behavior = move
quick-terminal-animation-duration = 0.08
GHOSTTY_EOF
    echo "✅ Ghostty configured"
    add_terminal_summary "wrote ghostty config: ~/.config/ghostty/config (theme: Catppuccin Mocha + macOS glass blur)"
    print_terminal_status
    print_terminal_summary
    print_terminal_next_steps

    echo ""
    echo "🎉 Terminal setup complete! Restart your terminal to apply changes."
}

# ============================================
# VS Code: Settings + Extensions
# ============================================
setup_vscode() {
    echo ""
    echo "📝 Setting up VS Code..."

    VSCODE_DIR="$HOME/Library/Application Support/Code/User"
    mkdir -p "$VSCODE_DIR"

    # Write settings.json
    backup_file "$VSCODE_DIR/settings.json"
    cat > "$VSCODE_DIR/settings.json" << 'VSCODE_SETTINGS_EOF'
{
  // ========== 信任设置 ==========
  "security.workspace.trust.untrustedFiles": "open",
  // ========== Claude Code ==========
  "claudeCode.preferredLocation": "panel",
  // ========== 工作台与界面 ==========
  "workbench.colorTheme": "Catppuccin Mocha",
  "workbench.iconTheme": "catppuccin-perfect-mocha",
  "workbench.startupEditor": "none",
  "workbench.list.smoothScrolling": true,
  "workbench.editor.enablePreview": true,
  "workbench.editor.enablePreviewFromQuickOpen": true,
  "breadcrumbs.enabled": true,
  // ========== Chat 视图 ==========
  "chat.viewSessions.orientation": "stacked",
  // ========== GitLens ==========
  "gitlens.ai.model": "vscode",
  "gitlens.ai.vscode.model": "copilot:gpt-4.1",
  // Security: do not persist personal tokens in setup scripts.
  // ========== 编辑器基础 ==========
  "editor.fontSize": 14,
  "editor.fontFamily": "'JetBrainsMono Nerd Font', 'Apple Color Emoji', 'Fira Code', 'Cascadia Code', Menlo, Monaco, monospace",
  "editor.fontLigatures": true,
  "editor.lineHeight": 1.6,
  "editor.minimap.enabled": false,
  "editor.cursorBlinking": "solid",
  "editor.smoothScrolling": true,
  "editor.wordWrap": "on",
  "editor.tabSize": 2,
  "editor.insertSpaces": true,
  "editor.detectIndentation": false,
  // ========== 保存与格式化 ==========
  "editor.formatOnSave": true,
  "editor.formatOnType": false,
  "editor.formatOnPaste": false,
  "editor.codeActionsOnSave": {
    "source.fixAll": "explicit",
    "source.organizeImports": "explicit"
  },
  "files.autoSave": "onFocusChange",
  "files.trimTrailingWhitespace": true,
  "files.insertFinalNewline": true,
  "files.trimFinalNewlines": true,
  // ========== 智能提示与补全 ==========
  "editor.semanticHighlighting.enabled": true,
  "editor.suggest.showClasses": true,
  "editor.suggest.showFunctions": true,
  "editor.suggest.showVariables": true,
  "editor.suggest.showKeywords": true,
  "editor.suggest.snippetsPreventQuickSuggestions": false,
  "editor.quickSuggestions": {
    "other": "on",
    "comments": "off",
    "strings": "off"
  },
  "editor.inlineSuggest.enabled": true,
  "editor.suggest.preview": true,
  "editor.suggestSelection": "first",
  // ========== 括号与引号 ==========
  "editor.autoClosingBrackets": "always",
  "editor.autoClosingQuotes": "always",
  "editor.autoClosingDelete": "always",
  "editor.autoClosingOvertype": "always",
  "editor.bracketPairColorization.enabled": true,
  "editor.guides.bracketPairs": "active",
  // ========== 终端配置 ==========
  "terminal.integrated.defaultProfile.osx": "fish",
  "terminal.integrated.fontSize": 13,
  "terminal.integrated.fontFamily": "'JetBrainsMono Nerd Font', 'Apple Color Emoji', Menlo, monospace",
  "terminal.integrated.scrollback": 10000,
  "terminal.integrated.cursorBlinking": false,
  "terminal.integrated.cursorStyle": "line",
  "terminal.integrated.sendKeyBindingsToShell": true,
  // ========== Git 集成 ==========
  "git.autofetch": true,
  "git.confirmSync": false,
  "git.enableSmartCommit": true,
  "git.pruneOnFetch": true,
  "git.branchSortOrder": "committerdate",
  // ========== 性能与隐私 ==========
  "telemetry.telemetryLevel": "off",
  "update.mode": "manual",
  "extensions.autoCheckUpdates": false,
  "extensions.autoUpdate": false,
  "search.exclude": {
    "**/node_modules": true,
    "**/dist": true,
    "**/build": true,
    "**/.git": true,
    "**/__pycache__": true,
    "**/*.pyc": true,
    "**/vendor": true,
    "**/go.sum": true
  },
  "files.watcherExclude": {
    "**/node_modules/**": true,
    "**/dist/**": true,
    "**/build/**": true,
    "**/.git/**": true,
    "**/__pycache__/**": true
  },
  // ========== Python 配置 ==========
  "[python]": {
    "editor.defaultFormatter": "charliermarsh.ruff",
    "editor.tabSize": 4,
    "editor.codeActionsOnSave": {
      "source.organizeImports": "explicit"
    },
    "editor.formatOnSave": true,
    "editor.rulers": [
      88,
      120
    ],
    "python.analysis.typeCheckingMode": "basic",
    "python.analysis.autoImportCompletions": true,
    "python.languageServer": "Pylance",
    "python.testing.pytestEnabled": true,
    "jupyter.notebookFileRoot": "${fileDirname}"
  },
  // ========== Go 配置 ==========
  "[go]": {
    "editor.defaultFormatter": "golang.go",
    "editor.tabSize": 4,
    "editor.insertSpaces": false,
    "editor.formatOnSave": true,
    "editor.rulers": [
      120
    ],
    "go.buildFlags": [],
    "go.lintFlags": [
      "--fast"
    ],
    "go.testFlags": [
      "-v",
      "-race"
    ],
    "go.useLanguageServer": true,
    "gopls": {
      "ui.semanticTokens": true,
      "ui.completion.usePlaceholders": true,
      "ui.diagnostic.analyses": {
        "unusedparams": true,
        "shadow": true,
        "nilness": true,
        "unusedwrite": true,
        "useany": true
      },
      "ui.modulediagnostics": true
    }
  },
  // ========== JavaScript 配置 ==========
  "[javascript]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode",
    "editor.tabSize": 2,
    "editor.formatOnSave": true,
    "editor.codeActionsOnSave": {
      "source.fixAll.eslint": "explicit"
    },
    "javascript.updateImportsOnFileMove.enabled": "always",
    "javascript.suggest.completeFunctionCalls": true,
    "javascript.suggest.includeAutomaticOptionalChainCompletions": true
  },
  // ========== TypeScript 配置 ==========
  "[typescript]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode",
    "editor.tabSize": 2,
    "editor.formatOnSave": true,
    "editor.codeActionsOnSave": {
      "source.fixAll.eslint": "explicit",
      "source.organizeImports": "explicit"
    },
    "typescript.updateImportsOnFileMove.enabled": "always",
    "typescript.suggest.completeFunctionCalls": true,
    "typescript.suggest.includeAutomaticOptionalChainCompletions": true,
    "typescript.tsserver.log": "off"
  },
  "[typescriptreact]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode",
    "editor.tabSize": 2,
    "editor.formatOnSave": true
  },
  "[json]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode",
    "editor.tabSize": 2,
    "editor.quickSuggestions": {
      "strings": true
    }
  },
  "[html]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode",
    "editor.tabSize": 2,
    "editor.autoClosingBrackets": "always"
  },
  "[css]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode",
    "editor.tabSize": 2,
    "editor.autoClosingBrackets": "always"
  },
  "[markdown]": {
    "editor.tabSize": 2,
    "editor.wordWrap": "on",
    "markdown.preview.breaks": true,
    "markdown.validate.enabled": true
  },
  "[yaml]": {
    "editor.tabSize": 2,
    "editor.insertSpaces": true,
    "editor.autoClosingBrackets": "never"
  },
  "[shellscript]": {
    "editor.tabSize": 2,
    "editor.insertSpaces": true
  },
  // ========== 建议补充配置 ==========
  // Error Lens - 行内显示错误,无需 hover
  "errorLens.enabledDiagnosticLevels": [
    "error",
    "warning",
    "info"
  ],
  "errorLens.delayMs": 300,
  // Bracket Colorization - 增强嵌套层次可读性
  "workbench.colorCustomizations": {
    "editorBracketHighlight.foreground1": "#FF6B6B",
    "editorBracketHighlight.foreground2": "#4ECDC4",
    "editorBracketHighlight.foreground3": "#45B7D1",
    "editorBracketHighlight.foreground4": "#96CEB4",
    "editorBracketHighlight.foreground5": "#FFEAA7",
    "editorBracketHighlight.foreground6": "#DDA0DD"
  },
  // 智能 Suggestions
  "editor.suggest.filterGraceful": true,
  "editor.suggest.localityBonus": true,
  "editor.suggest.shareSuggestSelections": true,
  // Accept Suggestion on Enter
  "editor.acceptSuggestionOnEnter": "smart",
  // Emmet 支持 (HTML/CSS 快速编写)
  "emmet.triggerExpansionOnTab": true,
  "emmet.includeLanguages": {
    "vue-html": "html",
    "plaintext": "html"
  },
  // Link Editing - 自动更新配对的标签/引用
  "editor.linkedEditing": true,
  // Peek Definition - 在不跳转的情况下查看定义
  "editor.peekDefinitionDefault": "peekAndDismiss",
  "git.mergeEditor": true,
  "diffEditor.renderIndicators": false,
  "diffEditor.maxComputationTime": 20000
}
VSCODE_SETTINGS_EOF
    echo "✅ VS Code settings configured"

    # Install extensions
    echo "📦 Installing VS Code extensions..."
    if ! command -v code &> /dev/null; then
        echo "⚠️  code CLI not found, skipping extension installation."
        echo "   Install it from VS Code: Cmd+Shift+P -> Shell Command: Install 'code' command in PATH"
        return
    fi

    EXTENSIONS=(
        "alefragnani.project-manager"
        "anthropic.claude-code"
        "catppuccin.catppuccin-vsc"
        "catppuccin.catppuccin-vsc-icons"
        "codezombiech.gitignore"
        "dbaeumer.vscode-eslint"
        "eamodio.gitlens"
        "formulahendry.auto-close-tag"
        "formulahendry.auto-rename-tag"
        "gbodeen.partial-diff-2"
        "github.copilot-chat"
        "golang.go"
        "gruntfuggly.todo-tree"
        "humao.rest-client"
        "ms-ceintl.vscode-language-pack-zh-hans"
        "ms-python.debugpy"
        "ms-python.python"
        "ms-python.vscode-pylance"
        "ms-python.vscode-python-envs"
        "oderwat.indent-rainbow"
        "thang-nm.catppuccin-perfect-icons"
        "usernamehw.errorlens"
        "vibe-island.terminal-focus"
        "yzhang.markdown-all-in-one"
        "ziyasal.vscode-open-in-github"
    )

    success_count=0
    failed_count=0
    failed_extensions=()

    for ext in "${EXTENSIONS[@]}"; do
        echo "  Installing $ext..."
        if code --install-extension "$ext" --force > /dev/null 2>&1; then
            success_count=$((success_count + 1))
        else
            failed_count=$((failed_count + 1))
            failed_extensions+=("$ext")
            echo "  ⚠️  Failed to install $ext"
        fi
    done
    echo "✅ VS Code extensions install complete: $success_count/${#EXTENSIONS[@]} succeeded"
    if [[ "$failed_count" -gt 0 ]]; then
        echo "⚠️  Failed extensions:"
        for ext in "${failed_extensions[@]}"; do
            echo "   - $ext"
        done
    fi

    echo ""
    echo "🎉 VS Code setup complete!"
}

# ============================================
# Main
# ============================================
echo "🚀 macOS Dev Environment Setup"
echo "   Mode: $MODE"

if [[ "$MODE" == "all" || "$MODE" == "terminal" ]]; then
    setup_shared
    setup_terminal
fi

if [[ "$MODE" == "all" || "$MODE" == "vscode" ]]; then
    setup_vscode
fi

echo ""
echo "🎉 All done!"
